# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_describtion', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='title_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.title'),
        ),
        migrations.AddField(
            model_name='questions',
            name='topic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.topic'),
        ),
        migrations.AddField(
            model_name='questions',
            name='track_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.track'),
        ),
    ]
