# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_describtion',
        ),
    ]
