# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_questions_question_describtion'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_programming_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, null=True)),
                ('option1', models.CharField(max_length=100, null=True)),
                ('option2', models.CharField(max_length=100, null=True)),
                ('option3', models.CharField(max_length=100, null=True)),
                ('option4', models.CharField(max_length=100, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='title_name',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='topic_name',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='track_name',
        ),
        migrations.AddField(
            model_name='title',
            name='topic_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='track_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.DeleteModel(
            name='topic',
        ),
        migrations.DeleteModel(
            name='track',
        ),
        migrations.AddField(
            model_name='c_programming_questions',
            name='title_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='quiz.title'),
        ),
        migrations.AddField(
            model_name='c_programming_questions',
            name='topic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='quiz.title'),
        ),
    ]
