# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20181029_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='title_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='topic_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='quiz.questions')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.topic')),
            ],
        ),
        migrations.CreateModel(
            name='track_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='c_programming_questions',
            name='title_name',
        ),
        migrations.RemoveField(
            model_name='c_programming_questions',
            name='topic_name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='topic_name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='track_name',
        ),
        migrations.AlterField(
            model_name='title',
            name='title_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='c_programming_questions',
        ),
        migrations.AddField(
            model_name='track_details',
            name='titles',
            field=models.ManyToManyField(to='quiz.title'),
        ),
        migrations.AddField(
            model_name='title_details',
            name='title_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.title'),
        ),
        migrations.AddField(
            model_name='title_details',
            name='topics',
            field=models.ManyToManyField(to='quiz.topic'),
        ),
    ]
