# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20181029_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
