# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_create_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_quiz',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
