# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20181029_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_quiz',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='create_quiz',
            name='updated_at',
        ),
    ]
