# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20181029_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='create_quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
