# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20181029_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_quiz',
            name='no_of_questions',
            field=models.IntegerField(null=True),
        ),
    ]
