# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20181029_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(default='ans', max_length=100),
        ),
    ]
