# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_questions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('questions_solved', models.ManyToManyField(to='quiz.questions')),
            ],
        ),
    ]
