# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_user_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_solved',
            name='questions_solved',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.questions'),
        ),
    ]
