# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20181031_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_solved',
            name='questions_solved',
            field=models.ManyToManyField(blank=True, to='quiz.questions'),
        ),
    ]
