# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20181031_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_solved',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
