# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20181031_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ques',
            field=models.TextField(max_length=1000),
        ),
    ]
