# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_quiz_questions_quiz_title_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_title_details',
            name='questions',
        ),
        migrations.AddField(
            model_name='create_quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.quiz_questions'),
        ),
        migrations.DeleteModel(
            name='quiz_title_details',
        ),
    ]
