# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20181101_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_quiz',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
