# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20181101_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='title_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
            ],
        ),
    ]
