# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_contest_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_scores',
            name='quiz_questions',
            field=models.ManyToManyField(blank=True, to='quiz.quiz_questions'),
        ),
    ]
