# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_contest_scores_quiz_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank_programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1000)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.title')),
            ],
        ),
    ]
