# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_rank_programming'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoreboard_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='rank_programming',
            name='title',
        ),
        migrations.DeleteModel(
            name='rank_programming',
        ),
    ]
