# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20181204_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreboard_track',
            old_name='title',
            new_name='track',
        ),
    ]
