# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20181204_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='programming_score',
        ),
        migrations.AddField(
            model_name='user_solved',
            name='correct_soleved',
            field=models.ManyToManyField(blank=True, related_name='correct', to='quiz.questions'),
        ),
        migrations.AddField(
            model_name='user_solved',
            name='wrong_solved',
            field=models.ManyToManyField(blank=True, related_name='wrong', to='quiz.questions'),
        ),
        migrations.AlterField(
            model_name='user_solved',
            name='questions_solved',
            field=models.ManyToManyField(blank=True, related_name='solved', to='quiz.questions'),
        ),
    ]
