# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20181217_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_solved',
            old_name='correct_soleved',
            new_name='correct_solved',
        ),
    ]
